name: Linux AppImage

on:
  push:
    branches:
      - platinum-mp
      - linux-native
      - ci/*
    tags:
      - project-pm-linux-v*
  pull_request:
    branches:
      - platinum-mp
  workflow_dispatch:

env:
  MELONDS_GIT_BRANCH: ${{ github.ref }}
  MELONDS_GIT_HASH: ${{ github.sha }}
  MELONDS_BUILD_PROVIDER: GitHub Actions
#  MELONDS_VERSION_SUFFIX: " RC"

permissions:
  contents: write

jobs:
  build:
    name: x86_64
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v6
      name: Check out sources
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install --allow-downgrades cmake ninja-build extra-cmake-modules libpcap0.8-dev libsdl2-dev libenet-dev \
          qt6-{base,base-private,multimedia}-dev qt6-wayland libqt6svg6-dev libarchive-dev libzstd-dev libfuse2 libfaad-dev
    - name: Configure
      run: cmake -B build -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DMELONDS_EMBED_BUILD_INFO=ON
    - name: Build
      run: |
        cmake --build build
        DESTDIR=AppDir cmake --install build
    - uses: actions/upload-artifact@v7
      with:
        name: melonDS-ubuntu-x86_64
        path: AppDir/usr/bin/melonDS
    - name: Fetch AppImage tools
      run: |
        wget https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
        wget https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage
        chmod a+x linuxdeploy-*.AppImage
    - name: Build the AppImage
      env:
        EXTRA_PLATFORM_PLUGINS: libqwayland-egl.so;libqwayland-generic.so
        EXTRA_QT_PLUGINS: waylandcompositor
        QMAKE: /usr/lib/qt6/bin/qmake
      run: |
        ./linuxdeploy-x86_64.AppImage --appdir AppDir --plugin qt --output appimage
    - uses: actions/upload-artifact@v7
      with:
        name: melonDS-ProjectPM-linux-x86_64.AppImage
        path: melonDS*.AppImage
        archive: false
    - name: Publish AppImage to the tagged release
      if: startsWith(github.ref, 'refs/tags/project-pm-linux-v')
      uses: softprops/action-gh-release@v2
      with:
        files: melonDS*.AppImage
